---
- name: "Jenkins job build"
  hosts: localhost
  collections: 
    - community.general
  tasks:
    - name: Create a jenkins build using basic authentication
      community.general.jenkins_build:
        name: "trial-freestyle"
        state: present
        user: supriya
        password: 12345
        url: http://localhost:8080
